version: "3"

services:
  app:
    build: app
    environment:
      - DB_HOST=db
      - DB_PORT=27017
    ports:
      - "8080:8000"
    networks:
      - appnet
    restart: on-failure
    depends_on:
      - db

  db:
    image: "mongo:3.0.15"
    command: "--smallfiles"
    ports:
      - "27017:27017"
    networks:
      - appnet

networks:
  appnet:
